#define TOKEN_KW_AND                           1
#define TOKEN_KW_OR                            2
#define TOKEN_EQ                               3
#define TOKEN_NE                               4
#define TOKEN_GT                               5
#define TOKEN_GE                               6
#define TOKEN_LT                               7
#define TOKEN_LE                               8
#define TOKEN_PLUS                             9
#define TOKEN_MINUS                           10
#define TOKEN_TIMES                           11
#define TOKEN_DIVIDE                          12
#define TOKEN_MODULO                          13
#define TOKEN_KW_NOT                          14
#define TOKEN_PERIOD                          15
#define TOKEN_LEFT_BRACKET                    16
#define TOKEN_NEWLINE                         17
#define TOKEN_ENDFILE                         18
#define TOKEN_KW_FUNCTION                     19
#define TOKEN_IDENTIFIER                      20
#define TOKEN_LEFT_PARENTHESIS                21
#define TOKEN_VARIADIC                        22
#define TOKEN_COMMA                           23
#define TOKEN_RIGHT_PARENTHESIS               24
#define TOKEN_KW_END                          25
#define TOKEN_KW_VAR                          26
#define TOKEN_RIGHT_BRACKET                   27
#define TOKEN_KW_IF                           28
#define TOKEN_KW_THEN                         29
#define TOKEN_KW_ELSE                         30
#define TOKEN_KW_FOR                          31
#define TOKEN_KW_FROM                         32
#define TOKEN_KW_TO                           33
#define TOKEN_KW_DO                           34
#define TOKEN_KW_IN                           35
#define TOKEN_KW_BY                           36
#define TOKEN_COLON                           37
#define TOKEN_INTEGER                         38
#define TOKEN_REAL                            39
#define TOKEN_STRING                          40
#define TOKEN_KW_TRUE                         41
#define TOKEN_KW_FALSE                        42
#define TOKEN_KW_INTEGER                      43
#define TOKEN_KW_NUMBER                       44
#define TOKEN_KW_STRING                       45
#define RULES_ERROR                           46
#define RULES_PROGRAM                         47
#define RULES_FUNCTION_LIST                   48
#define RULES_NEWLINE                         49
#define RULES_FUNCTION_DECL                   50
#define RULES_FUNCTION_DECL0                  51
#define RULES_FUNCTION_DECL1                  52
#define RULES_FUNCTION_DECLN                  53
#define RULES_OPT_TYPE                        54
#define RULES_STATEMENT_LIST                  55
#define RULES_STATEMENT                       56
#define RULES_VAR_DECLARATION                 57
#define RULES_STATEMENT_IF                    58
#define RULES_STATEMENT_FOR                   59
#define RULES_STATEMENT_THEN                  60
#define RULES_ASSIGNMENT                      61
#define RULES_CALL                            62
#define RULES_EXPRESSION                      63
#define RULES_VARIABLE                        64
#define RULES_EXPRESSION_IF                   65
#define RULES_STATEMENT_IF_THEN               66
#define RULES_STATEMENT_IF_THEN_ELSIF         67
#define RULES_FOR_BY                          68
#define RULES_PARAMETERS_CALL                 69
#define RULES_PARAMETERS_CALL_LIST            70
#define RULES_PARAMETER_CALL                  71
#define RULES_LITERAL                         72
#define RULES_TYPE                            73
